(function(){
'use strict';
var reduce=false;try{reduce=window.matchMedia('(prefers-reduced-motion: reduce)').matches;}catch(e){}
function safe(fn){try{fn();}catch(e){}}
function progress(){var bar=document.querySelector('.v6-progress i');if(!bar)return;var busy=false;function draw(){var d=document.documentElement;var max=Math.max(1,d.scrollHeight-window.innerHeight);var p=Math.max(0,Math.min(1,window.pageYOffset/max));bar.style.transform='scaleX('+p+')';busy=false;}function req(){if(!busy){busy=true;window.requestAnimationFrame(draw);}}draw();window.addEventListener('scroll',req,{passive:true});window.addEventListener('resize',req,{passive:true});}
function reveal(){if(reduce||!('IntersectionObserver' in window)||!Element.prototype.animate)return;var els=document.querySelectorAll('[data-v6-reveal]');var obs=new IntersectionObserver(function(entries){for(var i=0;i<entries.length;i++){var e=entries[i];if(e.isIntersecting){e.target.animate([{opacity:.25,transform:'translateY(18px)'},{opacity:1,transform:'translateY(0)'}],{duration:620,easing:'cubic-bezier(.16,1,.3,1)',fill:'none'});obs.unobserve(e.target);}}},{threshold:.08,rootMargin:'0px 0px -5% 0px'});for(var j=0;j<els.length;j++)obs.observe(els[j]);}
function consoleTilt(){if(reduce)return;var fine=false;try{fine=window.matchMedia('(pointer:fine)').matches;}catch(e){}if(!fine)return;var card=document.querySelector('.v6-console');if(!card)return;var rx=0,ry=0,cx=0,cy=0,raf=0;function tick(){cx+=(rx-cx)*.12;cy+=(ry-cy)*.12;card.style.transform='perspective(1000px) rotateX('+cy+'deg) rotateY('+cx+'deg)';if(Math.abs(rx-cx)>.02||Math.abs(ry-cy)>.02)raf=requestAnimationFrame(tick);else raf=0;}card.addEventListener('pointermove',function(ev){var r=card.getBoundingClientRect();rx=((ev.clientX-r.left)/r.width-.5)*3.6;ry=-((ev.clientY-r.top)/r.height-.5)*3;if(!raf)raf=requestAnimationFrame(tick);});card.addEventListener('pointerleave',function(){rx=0;ry=0;if(!raf)raf=requestAnimationFrame(tick);});}
function currentYear(){var y=document.querySelectorAll('[data-v6-year]');for(var i=0;i<y.length;i++)y[i].textContent=String(new Date().getFullYear());}
function boot(){safe(progress);safe(reveal);safe(consoleTilt);safe(currentYear);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
