(function(){
'use strict';
var MGI={email:'info@mgiglobalgroup.com',phoneDisplay:'+1 305-629-0491',phone:'13056290491',site:'https://mgiglobalgroup.com'};
var wa='https://wa.me/'+MGI.phone+'?text='+encodeURIComponent("Hi MGI, I'm interested in discussing outsourcing support for my company.");
var faqData=[
['What does MGI do?','MGI provides dedicated outsourced human capacity for sales-development, customer-support and back-office workflows, with a strong white-label model for agency partners.'],
['How does white-label delivery work?','Your agency retains the client relationship, strategy, brand, campaign direction and technology stack. MGI provides dedicated execution capacity aligned to the operating model you define.'],
['Can MGI work inside our existing CRM and dialer?','Where appropriate and approved, yes. The goal is to fit into your existing systems, permissions, scripts and reporting structure rather than force a separate stack.'],
['Can we begin with a small pilot?','Yes. A controlled pilot is often the best way to align the workflow, validate the operating model and define the path to scale.'],
['How quickly can a team be expanded?','Expansion timing depends on role complexity, volume, working hours, onboarding requirements and talent availability. MGI scopes this before launch rather than making a blanket guarantee.'],
['Do you serve companies outside the United States?','MGI is currently focused on clients in the United States, Canada and the United Kingdom.'],
['Where is MGI registered?','Miami Global Investments Group LLC is a Florida-registered limited liability company.'],
['Can MGI support different working hours?','Potentially. Working-hour coverage is scoped based on the engagement, required schedule and team availability.'],
['How is pricing determined?','Pricing is customized based on scope, volume, hours, skill requirements, campaign complexity and the number of dedicated seats.'],
['Do you provide the technology or work inside ours?','The preferred model is often to work inside the client or agency technology stack, subject to access and security requirements.'],
['How do you maintain quality?','Through documented workflows, onboarding, defined expectations, monitoring, QA checks, reporting and escalation paths appropriate to the engagement.'],
['Can agencies keep the client relationship completely under their own brand?','Yes. White-label partnerships are designed so the agency retains the relationship and brand while MGI supports delivery behind the scenes.']
];
function header(){
return '<a class="skip-link" href="#main">Skip to content</a>'+
'<header class="topbar'+(location.pathname==='/'?'':' inner')+'" id="topbar">'+
'<div class="container nav-wrap">'+
'<a class="brand" href="/" aria-label="MGI home"><img class="brand-mark" src="/assets/logo.svg" alt="MGI"><span>Miami Global Investments Group<small>Outsourcing &amp; BPO</small></span></a>'+
'<nav class="nav" id="nav" aria-label="Primary">'+
'<a href="/services/">Solutions</a><a href="/agency-partners/">Agency Partners</a><a href="/how-it-works/">How It Works</a><a href="/why-mgi/">Why MGI</a><a href="/about/">About</a><a href="/growth-strategy/">Expansion 2027</a><a href="/real-estate/">Real Estate</a><a href="/car-rental/">Car Rental</a><a href="/ai-solutions/">AI Solutions</a><a href="/news/">News</a><a href="/contact/">Contact</a><a class="btn btn-primary" data-track="booking_cta" href="/contact/#call">Book a Call <span class="arrow">→</span></a>'+
'</nav><button class="menu-btn" id="menu" type="button" aria-label="Open navigation" aria-expanded="false">☰</button></div></header>';
}
function footer(){
return '<footer class="footer"><div class="container"><div class="footer-grid">'+
'<div class="footer-brand"><a class="brand" href="/"><img class="brand-mark" src="/assets/logo.svg" alt="MGI"><span>MGI</span></a><p>Flexible operational capacity for agencies and growing businesses. Dedicated people, defined workflows and a pilot-to-scale model.</p><div class="footer-address"><strong>Florida Registered &amp; Mailing Address</strong><br>2125 Biscayne Blvd, Ste 204 #21720<br>Miami, FL 33137<br>USA</div></div>'+
'<div><h4>Solutions</h4><div class="footer-links"><a href="/services/white-label-sdr/">White-Label SDR</a><a href="/services/appointment-setting/">Appointment Setting</a><a href="/services/customer-support/">Customer Support</a><a href="/services/back-office/">Back Office</a></div></div>'+
'<div><h4>Partners</h4><div class="footer-links"><a href="/agency-partners/">Agency Partners</a><a href="/how-it-works/">How It Works</a><a href="/why-mgi/">Why MGI</a></div></div>'+
'<div><h4>Company</h4><div class="footer-links"><a href="/about/">About</a><a href="/growth-strategy/">2027 Growth Strategy</a><a href="/ai-solutions/">AI &amp; Automation</a><a href="/real-estate/">Real Estate</a><a href="/car-rental/">Car Rental</a><a href="/insights/">Insights</a><a href="/news/">News &amp; Media</a><a href="/results/">Results</a><a href="/contact/">Contact</a></div></div>'+
'<div><h4>Contact</h4><div class="footer-links"><a data-wa data-track="whatsapp_footer" href="'+wa+'" target="_blank" rel="noopener">WhatsApp</a><a data-track="phone_cta" href="tel:+13056290491">'+MGI.phoneDisplay+'</a><a href="mailto:'+MGI.email+'">'+MGI.email+'</a><span>Serving U.S. · Canada · UK</span></div></div>'+
'</div><div class="footer-bottom"><span>© <span data-year></span> Miami Global Investments Group LLC. All rights reserved.</span><span><a href="/privacy/">Privacy Policy</a> · <a href="/terms/">Terms of Use</a></span></div></div></footer>'+
'<a class="wa-fab" data-wa data-track="whatsapp_floating" href="'+wa+'" target="_blank" rel="noopener" aria-label="Chat with MGI on WhatsApp"><svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M12 3a8.5 8.5 0 0 0-7.26 12.92L3.5 20.5l4.69-1.22A8.5 8.5 0 1 0 12 3Zm0 15.2a6.7 6.7 0 0 1-3.42-.94l-.24-.14-2.78.72.74-2.7-.16-.26A6.7 6.7 0 1 1 12 18.2Zm3.67-5.02c-.2-.1-1.2-.59-1.39-.66-.18-.07-.32-.1-.45.1-.13.2-.52.66-.64.8-.12.13-.24.15-.44.05-.2-.1-.85-.31-1.61-1-.6-.53-1-1.19-1.12-1.39-.12-.2-.01-.3.09-.4.09-.09.2-.24.3-.36.1-.12.13-.2.2-.34.07-.13.03-.25-.02-.36-.05-.1-.45-1.08-.62-1.48-.16-.39-.33-.34-.45-.35h-.38c-.13 0-.35.05-.53.25-.18.2-.69.67-.69 1.64 0 .97.71 1.9.8 2.04.1.13 1.39 2.12 3.37 2.98.47.2.84.33 1.13.42.47.15.9.13 1.24.08.38-.06 1.2-.49 1.37-.96.17-.47.17-.87.12-.96-.05-.08-.18-.13-.38-.23Z"/></svg></a>';
}
function each(selector,fn){var nodes=document.querySelectorAll(selector);for(var i=0;i<nodes.length;i++){try{fn(nodes[i],i);}catch(e){}}}
function safe(fn){try{fn();}catch(e){}}
function injectChrome(){var h=document.querySelector('[data-header]');if(h)h.innerHTML=header();var f=document.querySelector('[data-footer]');if(f)f.innerHTML=footer();}
function setupNav(){var top=document.getElementById('topbar'),menu=document.getElementById('menu'),nav=document.getElementById('nav');function onScroll(){if(top){if(window.pageYOffset>14)top.classList.add('scrolled');else top.classList.remove('scrolled');}}onScroll();window.addEventListener('scroll',onScroll,{passive:true});if(menu&&nav){menu.addEventListener('click',function(){var open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open?'true':'false');menu.textContent=open?'×':'☰';document.body.classList.toggle('nav-open',open);});each('#nav a',function(a){a.addEventListener('click',function(){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.textContent='☰';document.body.classList.remove('nav-open');});});}each('.nav a',function(a){try{if(new URL(a.href,location.href).pathname===location.pathname)a.setAttribute('aria-current','page');}catch(e){}});}
function setupProgress(){var bar=document.querySelector('.scroll-progress span');if(!bar)return;var ticking=false;function update(){var doc=document.documentElement;var max=Math.max(1,doc.scrollHeight-window.innerHeight);var p=Math.min(1,Math.max(0,window.pageYOffset/max));bar.style.transform='scaleX('+p+')';ticking=false;}function request(){if(!ticking){ticking=true;window.requestAnimationFrame(update);}}update();window.addEventListener('scroll',request,{passive:true});window.addEventListener('resize',request,{passive:true});}
function setupReveal(){if(!('IntersectionObserver' in window)||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;var els=document.querySelectorAll('.reveal');if(!els.length)return;var obs;try{obs=new IntersectionObserver(function(entries){for(var i=0;i<entries.length;i++){if(entries[i].isIntersecting){entries[i].target.classList.add('is-visible');obs.unobserve(entries[i].target);}}},{threshold:.08,rootMargin:'0px 0px -5% 0px'});document.documentElement.classList.add('motion-ready');for(var i=0;i<els.length;i++){obs.observe(els[i]);}window.setTimeout(function(){each('.reveal',function(el){var r=el.getBoundingClientRect();if(r.top<window.innerHeight*1.08)el.classList.add('is-visible');});},90);}catch(e){document.documentElement.classList.remove('motion-ready');}}
function setupCounts(){var els=document.querySelectorAll('[data-count]');if(!els.length)return;if(!('IntersectionObserver' in window)){for(var i=0;i<els.length;i++)animateCount(els[i]);return;}var obs=new IntersectionObserver(function(entries){for(var i=0;i<entries.length;i++){if(entries[i].isIntersecting){animateCount(entries[i].target);obs.unobserve(entries[i].target);}}},{threshold:.35});for(var j=0;j<els.length;j++)obs.observe(els[j]);}
function animateCount(el){var end=parseInt(el.getAttribute('data-count'),10);if(isNaN(end)||el.getAttribute('data-done'))return;el.setAttribute('data-done','1');var suffix=el.getAttribute('data-suffix')||'';var start=performance.now?performance.now():Date.now(),dur=850;function tick(t){var now=t||Date.now();var p=Math.min(1,(now-start)/dur);var eased=1-Math.pow(1-p,3);el.textContent=Math.round(end*eased)+suffix;if(p<1)window.requestAnimationFrame(tick);}window.requestAnimationFrame(tick);}
function setupProcess(){var process=document.querySelector('.process-v2');if(!process)return;var ticking=false;function update(){var r=process.getBoundingClientRect();var vh=window.innerHeight||document.documentElement.clientHeight;var p=(vh-r.top)/(vh+r.height*.55);p=Math.max(0,Math.min(1,p));process.style.setProperty('--process-progress',p.toFixed(3));ticking=false;}function request(){if(!ticking){ticking=true;window.requestAnimationFrame(update);}}update();window.addEventListener('scroll',request,{passive:true});window.addEventListener('resize',request,{passive:true});}
function setupVisualDepth(){if(!window.matchMedia('(pointer:fine)').matches||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;var card=document.querySelector('.visual-frame');if(!card)return;var targetX=0,targetY=0,currentX=0,currentY=0,raf=0;function animate(){currentX+=(targetX-currentX)*.12;currentY+=(targetY-currentY)*.12;card.style.transform='perspective(900px) rotateX('+currentY+'deg) rotateY('+currentX+'deg) translateZ(0)';if(Math.abs(targetX-currentX)>.02||Math.abs(targetY-currentY)>.02)raf=requestAnimationFrame(animate);else raf=0;}card.addEventListener('pointermove',function(e){var r=card.getBoundingClientRect();targetX=((e.clientX-r.left)/r.width-.5)*4.5;targetY=-((e.clientY-r.top)/r.height-.5)*3.5;if(!raf)raf=requestAnimationFrame(animate);});card.addEventListener('pointerleave',function(){targetX=0;targetY=0;if(!raf)raf=requestAnimationFrame(animate);});}
function enhanceFAQ(){var acc=document.querySelector('.accordion');if(!acc)return;var existing={};each('.accordion summary',function(s){existing[s.textContent.replace(/^\s+|\s+$/g,'')]=true;});for(var i=0;i<faqData.length;i++){if(!existing[faqData[i][0]]){var d=document.createElement('details');d.innerHTML='<summary>'+faqData[i][0]+'</summary><p>'+faqData[i][1]+'</p>';acc.appendChild(d);}}each('.accordion details',function(d){d.addEventListener('toggle',function(){if(!d.open)return;each('.accordion details',function(other){if(other!==d&&other.open)other.open=false;});});});var entities=[];for(var j=0;j<faqData.length;j++){entities.push({'@type':'Question',name:faqData[j][0],acceptedAnswer:{'@type':'Answer',text:faqData[j][1]}});}try{var s=document.createElement('script');s.type='application/ld+json';s.text=JSON.stringify({'@context':'https://schema.org','@type':'FAQPage',mainEntity:entities});document.head.appendChild(s);}catch(e){}}
function setupLinks(){each('[data-year]',function(x){x.textContent=String(new Date().getFullYear());});each('[data-wa]',function(x){x.href=wa;});each('[data-track]',function(x){x.addEventListener('click',function(){try{window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:'mgi_cta',action:x.getAttribute('data-track'),path:location.pathname});if(typeof window.gtag==='function')window.gtag('event','mgi_cta',{cta_action:x.getAttribute('data-track'),page_path:location.pathname});}catch(e){}});});}
function setupForm(){var form=document.getElementById('lead-form');if(!form)return;var busy=false;form.addEventListener('submit',function(e){e.preventDefault();if(busy)return;if(form.reportValidity&&!form.reportValidity())return;var status=document.getElementById('form-status');var button=form.querySelector('[type="submit"]');var original=button?button.innerHTML:'';busy=true;if(button){button.disabled=true;button.textContent='Sending request…';}if(status){status.textContent='Sending your request securely…';status.setAttribute('aria-live','polite');}var data={},fd=new FormData(form);fd.forEach(function(v,k){data[k]=v;});fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}).then(function(r){return r.json().then(function(j){if(!r.ok)throw new Error(j.message||'Unable to send');return j;});}).then(function(){if(status)status.textContent='Thank you! Your inquiry has been received by MGI. Our team will review your requirements.';form.reset();try{window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:'generate_lead',form_name:'MGI contact',path:location.pathname});if(typeof window.gtag==='function')window.gtag('event','generate_lead',{form_name:'MGI contact',page_path:location.pathname});}catch(e){} }).catch(function(){if(status)status.innerHTML='We could not send your request right now. Please email <a href="mailto:'+MGI.email+'">'+MGI.email+'</a> or <a href="'+wa+'" target="_blank" rel="noopener">message us on WhatsApp</a>.';}).then(function(){busy=false;if(button){button.disabled=false;button.innerHTML=original;}});});}
function boot(){safe(injectChrome);safe(setupNav);safe(setupProgress);safe(setupLinks);safe(enhanceFAQ);safe(setupCounts);safe(setupProcess);safe(setupVisualDepth);safe(setupForm);safe(setupReveal);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();